### ISSUE TITLE
Open Joystick Display Server Config/Issue

### ISSUE THREAD

**Issue by 5kwatts** [RetroWeeb/open-joystick-display#4] opened 2019-05-10 04:25 UTC
Hi,

Thanks for this wonderful application.  I stream with 2 pcs and trying to get my input to display on the encoding pc.  I the display server on my gaming and the controller is connected (green circle) with the port displayed for 56709.  When I put that IP on the encoding display for the input driver and click reconnect, my controller isn't being recognized.  I've temporarily disabled the firewall, opened the ports with it enabled, I can ping both pcs from both machines but still no luck.  Is there something else I can try?  Is there a way I can get the error message/reason fail when it tries to connect?  Looking at setActive, can I see if response is the reason it is failing, or response.connected is the reason it is failing?  I know this is still in beta so wasn't sure if there was something I could do.

Thanks,
5k

**Comment by RetroWeeb** [comment] 2019-05-11 15:35
Good Morning @5kwatts,

That is odd. For funsies, can you open the OJD client on the same computer as the server and connect to 127.0.0.1:56709 and see if that works locally? If it does that means there is a network/firewall issue and I can help you attempt to debug it. If not, I'll have to figure out what is up (more than likely it doesn't like the port number).

Thanks!

**Comment by 5kwatts** [comment] 2019-05-11 21:16
Sure!  I'll give it a try later today or tomorrow and let you know.

Thanks

**Comment by 5kwatts** [comment] 2019-05-12 21:15
Hey Retro,

I tried it with my local IP:56709 that the server displays and 127.0.0.1:56709, and both of them tell me no joystick is connected.  When I click reconnect, should the bottom input tester display the controller, or do I have to press a button on my controller for it to show up?  I tried both ways and it doesn't display anything.  The server has a green circle on server/controller status before I click reconnect though on the client.

**Comment by RetroWeeb** [comment] 2019-05-12 22:01
Just to be clear, you followed these steps:

- Installed OJD Server on your Encoding Machine (For Testing)
- Opened OJD Server (on Encoding Machine) and activated the Joystick and Server (Two Green lights with the controller)
- Opened the OJD Client (on Encoding Machine) and went to Driver> Network > IP: 127.0.0.1:56709 > Reconnect

Just want to make sure those steps were followed before moving forward. I have a hunch something about your setup doesn't like the port. I only tried this feature on Linux and Windows 10.

**Comment by 5kwatts** [comment] 2019-05-13 03:55
Those are the steps that I did, but I did them on my gaming machine, not encoding machine but the behavior is the same.  My OS is Win 10.  The IP address in the OJD Server doesn't display 127.0.0.1:56709, it's gaming machine's IP.  Is that an issue?  Also the controller I am using is hori fighting commander, but it is recognized as an xbox controller.  Not sure if that is an issue or not and the controller works just fine in MK11 but wanted to mention it.

**Comment by RetroWeeb** [comment] 2019-05-13 23:04
Alright I will hold onto this ticket until I can figure out a better solution. My gut says the port number or the device it's binding to is the cause of the issue. I will look into it when I get time. Thanks!

**Comment by 5kwatts** [comment] 2019-05-14 02:52
No worries.  whatever I can do to help or help debug I'll be more than happy to help you out!  :)

**Comment by RetroWeeb** [comment] 2019-07-16 01:16
@5kwatts so I know it's been awhile, but I may have figured out the issue. If I get you a build are you willing to test again?

**Comment by RetroWeeb** [comment] 2019-07-16 23:20
https://drive.google.com/file/d/15fTC7k9gw3GWyn_AN48WqtoJwSdzN5-A/view?usp=sharing

Here is a beta build if you want to try it out. This should fix your network troubles. We found this out while doing some Nintendo Switch -> OJD networking testing. Let me know if anything comes up, otherwise I'm closing this ticket.

Thanks!

**Closed by RetroWeeb** 2019-07-16 23:20 UTC
Labels: bug
